version: '3.8'
services:
  app:
    build: .
    ports:
    - "8535:8535"
    depends_on:
      - db
    command: ["/bin/sh", "-c", "until nc -z db 5432; do sleep 1; done && ./app"]
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=content
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: